### ISSUE TITLE
add dark style

### ISSUE THREAD

**Issue by MichaelKreil** [versatiles-org/versatiles-style#19]

**Comment by MichaelKreil** [comment]
resolved in 737cd137ed5b47197b1100ff050e810373d9b625

**Comment by yetzt** [comment]
`eclipse` appears to be still missing from `/src/index.ts` and `/README.MD`

**Comment by MichaelKreil** [comment]
now it should be included
